// Turns data/seed/raw_wikidata.json (a raw Wikidata export) into
//   data/seed/institutions.json   (used by the site when Supabase is not configured)
//   supabase/seed.sql             (paste into the Supabase SQL editor)
// Run: node scripts/build-seed.mjs
// Source: Wikidata (CC0). All rows are marked is_test = true.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const raw = JSON.parse(readFileSync('data/seed/raw_wikidata.json', 'utf8').replace(/^﻿/, ''));

// How many of each (country, type) to keep. Only real records, nothing invented.
const QUOTA = {
  'GE:university': 16,
  'GE:school': 8,
  'KZ:university': 12,
  'KZ:college': 8,
  'KZ:school': 5,
};

// Institutions on disputed territories are left out until the owner decides how to
// treat them (SPEC.md section 5).
const EXCLUDE_SLUGS = new Set(['abkhazian-state-university', 'south-ossetian-state-university']);

const val = (x) => (x && x.value ? x.value : null);

function slugify(s) {
  return s
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

const seen = new Set();
const counts = {};
const used = new Set();
const out = [];

// Prefer records with an English name and a website: they make the better test data.
const score = (r) => (val(r.row.en) ? 2 : 0) + (val(r.row.site) ? 1 : 0);
const sorted = [...raw].sort((a, b) => score(b) - score(a));

for (const r of sorted) {
  const key = `${r.country}:${r.type}`;
  const qid = val(r.row.item).split('/').pop();
  if (!(key in QUOTA) || seen.has(qid)) continue;
  if ((counts[key] ?? 0) >= QUOTA[key]) continue;

  const m = /Point\(([-\d.]+) ([-\d.]+)\)/.exec(val(r.row.coord) ?? '');
  if (!m) continue;
  const lng = Number(m[1]);
  const lat = Number(m[2]);

  const en = val(r.row.en);
  const nat = val(r.row.nat);
  const original = (r.country === 'GE' ? val(r.row.ka) : null) ?? nat ?? val(r.row.ru) ?? en;
  if (!en) continue; // every test record needs an English name
  if (EXCLUDE_SLUGS.has(slugify(en))) continue;

  const names = { original: original ?? en };
  for (const l of ['en', 'ru', 'ka', 'es', 'zh']) {
    const v = val(r.row[l]);
    if (v) names[l] = v;
  }

  const base = slugify(en ?? '') || qid.toLowerCase();
  let slug = base;
  if (used.has(`${r.country}/${slug}`)) slug = `${base}-${qid.toLowerCase()}`;
  used.add(`${r.country}/${slug}`);

  const city = val(r.row.cityL);
  const inc = val(r.row.inc);
  seen.add(qid);
  counts[key] = (counts[key] ?? 0) + 1;
  out.push({
    slug,
    type: r.type,
    country: r.country,
    city: city ? { en: city } : {},
    names,
    lat: Math.round(lat * 1e6) / 1e6,
    lng: Math.round(lng * 1e6) / 1e6,
    website: val(r.row.site),
    foundedYear: inc ? Number(inc.slice(0, 4)) || null : null,
    externalIds: { wikidata: qid },
  });
}

out.sort((a, b) => (a.country + a.type + a.slug).localeCompare(b.country + b.type + b.slug));
mkdirSync('data/seed', { recursive: true });
writeFileSync('data/seed/institutions.json', JSON.stringify(out, null, 2) + '\n', 'utf8');

const q = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const rows = out.map(
  (i) =>
    `  (${q(i.slug)}, ${q(i.type)}, ${q(i.country)}, ${q(JSON.stringify(i.city))}::jsonb, ${q(
      JSON.stringify(i.names),
    )}::jsonb, extensions.ST_SetSRID(extensions.ST_MakePoint(${i.lng}, ${i.lat}), 4326)::extensions.geography, ${q(i.website)}, ${
      i.foundedYear ?? 'null'
    }, ${q(JSON.stringify(i.externalIds))}::jsonb)`,
);
const sql = `-- Test seed: ${out.length} real institutions from Wikidata (CC0), marked is_test = true.
-- Generated by scripts/build-seed.mjs. Safe to run again: it first removes old test rows.
delete from public.institutions where is_test;

insert into public.institutions
  (slug, type, country, city, names, location, website, founded_year, external_ids, is_test)
select v.*, true from (values
${rows.join(',\n')}
) as v(slug, type, country, city, names, location, website, founded_year, external_ids);
`;
mkdirSync('supabase', { recursive: true });
writeFileSync('supabase/seed.sql', sql, 'utf8');

console.log(`Wrote ${out.length} institutions`, counts);
