// Checks the drafts in data/drafts/ (format: DATA_COLLECTION.md) and writes
//   supabase/data/drafts.sql             the cards stored as DRAFTS (hidden from the public)
//   supabase/data/drafts_published.sql   the same cards PUBLISHED (visible, used by the matching)
//   docs/review/REVIEW.md                a readable report for the owner: what was found, from where, how sure
// Run: npm run data:import
// Publish only what the owner has read in REVIEW.md.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import {
  countryDraftToSql,
  institutionDraftToSql,
  institutionReview,
  validateCountryDraft,
  validateInstitutionDraft,
} from '../src/lib/data/draft.ts';

const root = 'data/drafts';

const readJson = (file: string): unknown => JSON.parse(readFileSync(file, 'utf8').replace(/^﻿/, ''));
const files = (dir: string): string[] =>
  existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
        e.isDirectory() ? files(path.join(dir, e.name)) : e.name.endsWith('.json') ? [path.join(dir, e.name)] : [],
      )
    : [];

const header = (mode: string) => [
  `-- Cards of institutions and countries. Generated by scripts/import-drafts.mts (${mode}).`,
  `-- Run AFTER the institutions import. Safe to run again: each card replaces its previous version.`,
  '',
];
const sqlDraft = header('stored as drafts');
const sqlPublished = header('PUBLISHED');
const review: string[] = ['# Отчёт о собранных данных', '', 'Прочитайте и, если всё верно, выполните `supabase/data/drafts_published.sql`.', ''];
const problems: string[] = [];
let institutions = 0;
let programs = 0;
let countries = 0;

for (const file of files(path.join(root, 'institutions'))) {
  const slug = path.basename(file, '.json');
  const result = validateInstitutionDraft(readJson(file));
  if (!result.ok) {
    problems.push(`${file}:\n  ${result.errors.join('\n  ')}`);
    continue;
  }
  institutions++;
  programs += result.data.programs.length;
  const title = `-- ${result.data.institution.country}/${slug}`;
  sqlDraft.push(title, institutionDraftToSql(result.data, slug, { publish: false }), '');
  sqlPublished.push(title, institutionDraftToSql(result.data, slug, { publish: true }), '');
  review.push(institutionReview(result.data, slug, result.warnings));
}

for (const file of files(path.join(root, 'countries'))) {
  const result = validateCountryDraft(readJson(file));
  if (!result.ok) {
    problems.push(`${file}:\n  ${result.errors.join('\n  ')}`);
    continue;
  }
  countries++;
  const title = `-- country ${result.data.country}`;
  sqlDraft.push(title, countryDraftToSql(result.data, { publish: false }), '');
  sqlPublished.push(title, countryDraftToSql(result.data, { publish: true }), '');
  review.push(
    `### Страна ${result.data.country}`,
    '',
    `- Валюта: ${result.data.currency}; работа во время учёбы: ${result.data.work_during_study.allowed ?? 'нет данных'}; рабочая виза после учёбы: ${result.data.post_study_work_visa.available ?? 'нет данных'}`,
    `- Стоимость жизни: ${result.data.cost_of_living.map((c) => `${c.city.en ?? '?'} ${c.amount_per_month ?? '?'} ${c.currency}/мес`).join('; ') || 'нет данных'}`,
    result.data.notes_for_reviewer ? `- Заметки: ${result.data.notes_for_reviewer}` : '',
    '',
  );
}

if (problems.length) {
  console.error(`Drafts with errors (${problems.length}):\n` + problems.join('\n'));
  process.exitCode = 1;
}

mkdirSync('supabase/data', { recursive: true });
mkdirSync('docs/review', { recursive: true });
writeFileSync('supabase/data/drafts.sql', sqlDraft.join('\n') + '\n');
writeFileSync('supabase/data/drafts_published.sql', sqlPublished.join('\n') + '\n');
writeFileSync('docs/review/REVIEW.md', review.join('\n') + '\n');
console.log(`${institutions} institutions, ${programs} programmes, ${countries} countries -> supabase/data/drafts*.sql, docs/review/REVIEW.md`);
